# Node.js with React

# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true # so inicia o proximo build quando o anterior terminar agrupando os commits
  branches:
    include:
      - staging

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm config set legacy-peer-deps true
    displayName: "npm legacy-peer-deps"

  - script: |
      npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    displayName: "npm registry auth token"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "build"
      includeRootFolder: true
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "staging"
      publishLocation: "Container"
